proxmox_nodes:
  hosts:
    pve1:
      ansible_host: 192.168.68.90
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible_proxmox
      ansible_ssh_common_args: '-o IdentitiesOnly=yes'
