services:
  generator:
    build: generator/
    image: edge-generator:2026-03-13
    container_name: edge-generator
    command: [ "python", "/app/generator.py"]
    volumes:
      - /srv/appdata/edge_data:/srv/appdata/edge

  coredns:
    image: coredns/coredns:1.11.1
    container_name: coredns
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /srv/appdata/edge_data/coredns_data/Corefile:/Corefile:ro
    command: -conf /Corefile

  caddy:
    build:
      context: ./caddy
    container_name: caddy
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - ./.env
    volumes:
      - /srv/appdata/edge_data/caddy_data/Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/appdata/edge_data/caddy_data:/data
      - /srv/appdata/edge_data/caddy_config:/config
