services:
  generator:
    build: generator/
    image: edge-generator:2026-03-13
    container_name: edge-generator
    command: ["python", "/app/generator.py"]
    volumes:
      - ${APPDATA_ROOT}/edge_data:/edge_data

  coredns:
    image: coredns/coredns:1.11.1
    container_name: coredns
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${APPDATA_ROOT}/edge_data/config/Corefile:/Corefile:ro
    command: -conf /Corefile

  caddy:
    build:
      context: ./caddy
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./.env
    volumes:
      - ${APPDATA_ROOT}/edge_data/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${APPDATA_ROOT}/edge_data/data:/data
      - ${APPDATA_ROOT}/edge_data/config:/config
