services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=50
      - HBOX_OPTIONS_ALLOW_REGISTRATION=false
    ports:
      - "3100:7745"
    volumes:
      - ./data/homebox_data:/data
