- name: Configure new LXC
  hosts: "smb.local"
  gather_facts: false
  tasks:

    - name: Start and enable nginx
      ansible.builtin.service:
        name: smbd
        state: started
        enabled: true
